<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('robots_txt', function (Blueprint $table) {
            $table->id();
            $table->text('content');
            $table->timestamp('last_generated_at')->nullable();
            $table->foreignId('updated_by')->nullable()->constrained('users')->onDelete('set null');
            $table->timestamps();

            $table->unique('id');
        });

        // Insert default robots.txt
        $defaultContent = implode("\n", [
            '# Robots.txt',
            '# Generated by Blog CMS',
            '# Last updated: ' . now()->toDateTimeString(),
            '',
            'User-agent: *',
            'Allow: /',
            'Disallow: /admin',
            'Disallow: /api',
            'Disallow: /storage',
            '',
            '# Crawl-delay (optional)',
            '# Crawl-delay: 1',
            '',
            '# Sitemap',
            'Sitemap: ' . url('/sitemap.xml'),
            '',
            '# Disallow specific file types',
            'Disallow: /*.pdf$',
            'Disallow: /*.doc$',
            'Disallow: /*.docx$',
            '',
            '# Allow common bots',
            'User-agent: Googlebot',
            'Allow: /',
            '',
            'User-agent: Bingbot',
            'Allow: /',
        ]);

        \DB::table('robots_txt')->insert([
            'content' => $defaultContent,
            'last_generated_at' => now(),
        ]);
    }

    public function down()
    {
        Schema::dropIfExists('robots_txt');
    }
};
